Added HSTS checks
sensu-plugins/sensu-plugins-ssl pull request #32
Opened 2017-09-20 18:17 UTC by rwky

* check-ssl-hsts-preload.rb - for checking the preload status of a domain
* check-ssl-hsts-preloadable.rb - for checking if a domain can be preloaded

## Pull Request Checklist

**Is this in reference to an existing issue?** - No

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

Added HSTS checks

#### Known Compatability Issues
 None

2017-09-23 17:08 UTC, majormoses commented
@rwky thanks for the contribution, can you take a look at the failing tests?

2017-09-23 20:40 UTC, rwky commented
The travis logs show the failures are in check-java-keystore-cert_spec.rb which isn't something I've modified.

2017-09-23 20:53 UTC, majormoses commented
Sorry I saw master was passing and this was failing and did not look farther than that.

2017-09-23 20:59 UTC, majormoses requested changes
Just a few tweaks, also I need a testing artifact [per](https://github.com/sensu-plugins/community/blob/master/PULL_REQUEST_PROCESS.md#7-testing-artifacts)

2017-09-23 20:59 UTC, majormoses commented on bin/check-ssl-hsts-preloadable.rb
> +  API_URL = 'https://hstspreload.org/api/v2/preloadable'.freeze
expose this through a an option, if they ever change the URL it is better to give people the option to change it via a param while awaiting a code change and release to update default.

2017-09-23 20:59 UTC, majormoses commented on bin/check-ssl-hsts-preloadable.rb
> +    warning 'Bad response recieved from API' unless response.is_a?(Net::HTTPSuccess)
I think we might want to handle a redirection rather than simply saying its bad.

2017-09-23 20:59 UTC, majormoses commented on bin/check-ssl-hsts-status.rb
> +  API_URL = 'https://hstspreload.org/api/v2/status'.freeze
expose this through a an option, if they ever change the URL it is better to give people the option to change it via a param while awaiting a code change and release to update default.

2017-09-23 20:59 UTC, majormoses commented on bin/check-ssl-hsts-status.rb
> +    warning 'Bad response recieved from API' unless response.is_a?(Net::HTTPSuccess)
I think we might want to handle a redirection rather than simply saying its bad.

2017-09-26 06:28 UTC, majormoses commented
@rwky looks like @eheydrick fixed up the java keystore issue, now looks just like some linting errors.

2017-09-26 06:36 UTC, eheydrick commented
Hi @rwky, first off thanks for contributing your plugins to the project! I took a look at that failing tests and found that it started failing when the build moved from Ubuntu Precise to Trusty travis workers. Something in openssl or keytool changed such that the java keystore check was unable to read the cert stored in the keystore. I pushed a fix (https://github.com/rwky/sensu-plugins-ssl/commit/2fcce4b263a31fed63e8549d65b2b52fbdce1d5f) up to your fork and the spec tests are now passing. 

However there are rubocop issues to resolve. Can you take a look at the failures at https://travis-ci.org/sensu-plugins/sensu-plugins-ssl/jobs/279823467.

2017-09-26 07:43 UTC, rwky commented
:+1: I'll look at the changes this week

2017-09-26 15:53 UTC, rwky commented
Rubocop is now happy and I've added tests. I've made the changes @majormoses requested.

I'm not particularly familiar with Ruby (this was a fun learning experience) so let me know if you need me to look into modifying anything else.

2017-09-26 16:06 UTC, majormoses commented
@rwky thanks for fixing that up so quickly I will get this merged and released if I can before my scrum if not I should get it some time this morning.

2017-09-26 16:06 UTC, majormoses approved these changes

2017-09-26 16:17 UTC, merged

2017-09-26 17:21 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-ssl/versions/1.5.0